# Generated by Django 3.2.8 on 2021-11-15 11:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilar',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
