# Generated by Django 3.2.8 on 2021-11-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncelleme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
    ]
